incr-13
syols/go-devops pull request #4
Opened 2022-07-05 22:10 UTC by syols

2022-07-11 20:42 UTC, Perederey requested changes
В целом отличный PR, но надо переделать несколько вещей

1) Ошибка должна только возвращаться, а не передавать аргументом
2) Надо использовать context для базы данных.

 PR получился огромный, мог что-то пропустить ;)

2022-07-11 20:42 UTC, Perederey commented on cmd/server/server_test.go
> +		Store: config.StoreConfig{
кстати, default значения не обязательно указывать, структура создаться автоматически и для теста пустые структуры можно просто пропустить.

2022-07-11 20:42 UTC, Perederey commented on config/config.go
> +func NewConfig() (settings Config) {
не совсем понятно, а зачем тебе тогда публичные методы, если ты Options вызываешь только внутри, не совсем понятно.

2022-07-11 20:42 UTC, Perederey commented on internal/app/client.go
> +	}
лучше возвращать ошибку, а не логать ее, то есть post должен возвращать ошибку

`func (c *Client) post(metricName string, metricValue string, metricAlias string) error` 

Также ты можешь объединить metricName, metricValue, metricAlisas в одну структуру и просто передавать Metric

`func (c *Clinet) post(m Metric) error`

2022-07-11 20:42 UTC, Perederey commented on internal/app/server.go
> +		<-sign
а что если сигнал по какой-то причине не придет?

2022-07-11 20:42 UTC, Perederey commented on internal/errors/metric.go
> +func (e *TypeNameError) Error() string {
не совсем понимаю, а почему именно с указателем тут функция? 

Есть два способа передачи функций:

```go
func (e TypeNameError) Error() string {}

func (e *TypeNameError) Error() string{}
```

Разница в том, что в первом случае копируется структура, а во втором копируется указатель.
Но, указатель не ускоряет работу, а зачастую замедляет.

Их удобно использовать, когда тебе нужно саму структуру поменять, например, если бы ты хотел поменять имя пользователя. Тогда указатель использовать удобно.
Но я а если, ты возвращаешь что-то, то указатель избыточен.

2022-07-11 20:42 UTC, Perederey commented on internal/errors/metric.go
> +}
по-факту избыточная структура, у тебя тут обертка для строк, я бы просто бы использовал бы стандартную ошибку тут.

2022-07-11 20:42 UTC, Perederey commented on internal/handlers/healthcheck.go
> +func Ping(metrics store.MetricsStorage, _ *string, w http.ResponseWriter, _ *http.Request) {
я бы все же бы разбил вот так

```go
func Ping(storage store.MetricStorage) http.HandlerFunc {
    return func(w http.ResponseWriter, _ *http.Request) {
   
    }
}
```

2022-07-11 20:42 UTC, Perederey commented on internal/store/database.go
> +func (d DatabaseStore) Load() ([]models.Payload, error) {
Надо обязательно использовать context, первым аргументом, а то у тебя получается все без context.

// где-то в handler создаешь вот такой контектс
ctx, cancel := context.WithTimeout(r.Context(), 5 * time.Seconds)
defer cancel()
// где нужно вызвать метод d.Load(ctx, models)

2022-07-18 17:13 UTC, syols commented on cmd/server/server_test.go
> +		Store: config.StoreConfig{
Готово

2022-07-18 17:14 UTC, syols commented on config/config.go
> +func NewConfig() (settings Config) {
Заменил на приватные

2022-07-18 17:15 UTC, syols commented on internal/app/client.go
> +	}
Упростил логику агента

2022-07-18 17:15 UTC, syols commented on internal/app/server.go
> +		<-sign
 Добавил контекст

2022-07-18 17:16 UTC, syols commented on internal/errors/metric.go
> +func (e *TypeNameError) Error() string {
Это была попытка поиграться с кастомными ошибками, в текущей версии удалил и замечание учел)

2022-07-18 17:17 UTC, syols commented on internal/errors/metric.go
> +}
Удалил

2022-07-18 17:18 UTC, syols commented on internal/handlers/healthcheck.go
> +func Ping(metrics store.MetricsStorage, _ *string, w http.ResponseWriter, _ *http.Request) {
Поправил во всех обработчиках

2022-07-18 17:18 UTC, syols commented on internal/store/database.go
> +func (d DatabaseStore) Load() ([]models.Payload, error) {
Добавил немного контекста)

2022-07-19 20:38 UTC, sergeysergeevru approved these changes
Привет) Смотрится хорошо. Посмотрел исправления согласно комментариям Саши - все верно. Добавил пару ремарок от себя. Спасибо)

2022-07-19 20:38 UTC, sergeysergeevru commented on internal/handlers/update.go
> +	if err, ok := err.(validator.ValidationErrors); ok {
предпочитаю использовать errors.As, иначе если где-то ошибка будет обернута то скастовать ее не получится

2022-07-19 20:38 UTC, sergeysergeevru commented on internal/store/database.go
> +	db, err := sqlx.ConnectContext(ctx, "postgres", d.dataSourceName)
Создание коннекта к базе довольно ресурсоемкая задача, поэтому стоит его переиспользовать. Иначе возникает две проблемы. Одна это больший латенси на респонсе. Другая проблема в том, что на большом трафике можно израсходовать все доступные коннекты к базе, если будем обращаться в ней одновременно.

2022-07-19 21:05 UTC, merged